apiVersion: v1
kind: Service
metadata:
  name: customers-svc
  labels:
    app: AIT Template
    service: customers
spec:
  selector:
    app: AIT Template
    service: customers
  ports:
    - name: http-port
      port: 3000
